#Lab01_Task2__ElyasSequeira
print("calculator")
V1 = int(input("Please enter your first value:"))
V2 = int(input("Please enter your second value:"))
a = (V1 + V2) 
s = (V1 - V2)
m = (V1 * V2)
d = (V1 / V2)
print("Sum = " +str(a))
print("Difference= " +str(s))
print("Product= " +str(m))
print("Quotient = " +str(d))